### ISSUE TITLE
Erro deposito 3 casas decimais

### ISSUE THREAD

**Issue by paulopatto** [gympasstest/bank_system#2]
Eu tinha R$ 200,00 em minha conta, ai efetuei o deposito de R$ 0.001 em minha conta, o sistema mostra que o deposito foi feito com sucesso, mas esse valor não aparece em minha conta. 

Esse é um comportamento esperado ou ele deveria bloquear esse tipo de deposito? 

![deposito de 0 001 deito com sucesso](https://user-images.githubusercontent.com/105045/27757677-faa10a1a-5dda-11e7-8d31-ab8b07b176d0.png)

Eu fiz 10 depósitos de R$ 0,001, e ao final destas operações esperava ter R$ 0,01 em minha conta, pois os depósitos foram feitos com sucesso. Mas ao final destas operações meu saldo era de R$ 200,00.

O banco ficou com meu dinheiro?

**Comment by gympasstest** [comment]
Corrigido. Todo depósito tem que ser maior que 1 real. O banco não fica mais com seu dinheiro.
