### ISSUE TITLE
Digito de conta

### ISSUE THREAD

**Issue by paulopatto** [gympasstest/bank_system#3]
Por que é gerado um digito no algoritmo de geração de número da conta, sendo que ele não é usado?

```ruby 
Account.new.account_number_gen
# => "61523-5"
```
O campo de número da conta é inteiro:

```ruby
Account(id: integer, agency_number: integer, account_number: integer, balance: float, status: boolean, user_id: integer...)
```
E esse digito não é salvo:

```ruby
Account.first

#<Account:0x00560e73562ac0
 id: 1,
 agency_number: 5367,
 account_number: 61523,
 balance: 200.0,
 status: false
...>
```

Se eu mostrar essa informação ao usuário com número de conta, vou ter um problema não?

**Comment by gympasstest** [comment]
Corrigido. Número da conta sendo gerada sem adicionar o digito no final.

**Comment by paulopatto** [comment]
:+1:
